swagger: '2.0'
schemes:
  - http
host: petstore.swagger.io
basePath: /v2
info:
  description: <%= description %>
  version: <%= version %>
  title: <%= name %>
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: <%= username %>
    email: <%= email %>
  x-logo:
    url: 'https://rebilly.github.io/ReDoc/petstore-logo.png'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
tags:
  - name: Pagination
    x-traitTag: true
    description: Pagination description
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/api/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
